# Site settings
title: "گروه کاربران لینوکس سنندج"
motto: "اجتماع دوستداران لینوکس سنندج"
author: Hamid Saydi
email: gshs99@gmail.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sanlug.ir" # the base hostname & protocol for your site
keywords: "کامپیوتر، لینوکس، لاگ، سنندج"
copyright: "Commons Attribution 4.0 International"
robot: ""
description: > # this means to ignore newlines until "baseurl:"
  گروه کاربران لینوکس سنندج

long_description: >
  سنندج لاگ اجتماع آزادي از دوست‌داران گنو/لينوکس است که بيشتر در شهرسنندج  زندگي مي‌کنند. ما از شما دعوت مي‌کنيم به اجتماع ما بپيونديد.ما در فيسبوک تويتر تلگرام ،گوگل پلاس و اکثر شبکه هاي اجتماعي فعاليت ميکنيم.شما همينطور ميتوانيد از طريق همين سايت و يا شبکه هاي اجتماعي از زمان برگزاري جلسات و ساير رويداد ها آگاه شويد.
twitter_username: sanlug
github_username:  sanlug
fullname: "گروه کاربران لینوکس سنندج"
favicon: "assets/img/favicon.png"


#outputting
permalink: :title.html

# Build settings
markdown: Markright
kramdown:
    coderay_line_numbers: nil
encoding: utf-8
timezone: Europe/Berlin

paginate: 5
paginate_path: "/page:num/"

tag_page_layout: tag_page
tag_page_dir: tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      author: "حمید صیدی"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: "حمید صیدی"
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project

gems:
  - jekyll-sitemap
  - jalalidate
  - coderay
  - jekyll-paginate

collections:
  projects:
    output: true
